import pickle
from dataclasses import dataclass

import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split


@dataclass
class Probe:
    layer: int
    ridge_v: Ridge
    ridge_a: Ridge
    r2_v: float
    r2_a: float

    def predict(self, hidden: np.ndarray) -> np.ndarray:
        return np.stack([self.ridge_v.predict(hidden),
                         self.ridge_a.predict(hidden)], axis=1)


def collect_word_states(model, words, templates) -> np.ndarray:
    out = []
    for w in words:
        per_tmpl = [model.hidden_states(t.format(w=w))[:, -1, :] for t in templates]
        out.append(np.mean(per_tmpl, axis=0))  # [n_layers, d]
    return np.stack(out)


def train_probe(states, v_targets, a_targets, alpha, test_frac, seed=0) -> Probe:
    n_layers = states.shape[1]
    idx_tr, idx_te = train_test_split(np.arange(len(states)), test_size=test_frac,
                                      random_state=seed)
    best = None
    for layer in range(n_layers):
        X_tr, X_te = states[idx_tr, layer], states[idx_te, layer]
        rv = Ridge(alpha=alpha).fit(X_tr, v_targets[idx_tr])
        ra = Ridge(alpha=alpha).fit(X_tr, a_targets[idx_tr])
        r2v = r2_score(v_targets[idx_te], rv.predict(X_te))
        r2a = r2_score(a_targets[idx_te], ra.predict(X_te))
        if best is None or r2v > best.r2_v:
            best = Probe(layer, rv, ra, r2v, r2a)
    return best


def save_probe(probe, path):
    with open(path, "wb") as f:
        pickle.dump(probe, f)


def load_probe(path) -> Probe:
    # Safe: probe.pkl is generated by this codebase, not from untrusted sources
    with open(path, "rb") as f:
        return pickle.load(f)
