"""coherence_collinearity — is the rule effect the geometry, or the coherence the geometry produces?

`rule_vs_text` established a rule effect of +0.024 on associative drift but could not interpret it.
polygon-pca's four builds spanned line coherence 0.653-0.759 and the walk's spanned 0.823-0.859 —
**disjoint ranges**, so "rule" and "coherence" were the same contrast and the r = -0.77 across those
eight poems was the rule effect rewritten, not independent evidence for either.

**Reordering was tried first and rejected.** Permuting the lines of a fixed build is the ideal
manipulation — it holds the line multiset exactly constant — but it is far too weak here: greedy
max- and min-coherence reorderings move a build only 0.05-0.10, because coherence is mostly a
property of *which* lines a rule selects, not what order they sit in. The resulting overlap band
would have held three polygon builds against two walk builds.

**So: build a coherence-response curve inside one rule family, and ask whether the other rule lies
on it.** The walk's `w` already controls coherence (`weighted_selection`, rho +1.00). Measured under
this mask and length it spans 0.561 (w = 0) to 0.859 (w = 0.3+), straddling polygon's entire range.

    walk family     w in {0, .04, .07, .1, .3} x 4 origins = 20 builds, coherence 0.544-0.859
    polygon family  4 origins                              =  4 builds, coherence 0.653-0.759

The intermediate weights are chosen to populate polygon's own range rather than to space `w`
evenly: w = 0.04 lands all four origins inside 0.653-0.759, so the matched-coherence band holds
seven walk builds against four polygon ones instead of the four it would hold otherwise.

Eight of the twenty-four were generated by `rule_vs_text` (walk w = 0.3 and all four polygon builds)
and are reused from its cache after the rebuilt text is verified against `rule_vs_text_poems.md`.

**The test.** Fit drift against coherence across the 16 walk builds — a within-family curve with
real span and real n, unlike the n = 4 slopes that could not be read before. Then take each polygon
build's residual from that curve.

    polygon lands ON the walk curve      -> the "rule effect" was coherence all along
    polygon lands ABOVE it at matched coherence -> the geometry does something coherence does not

A matched-coherence contrast over the overlap band is reported alongside, since it assumes no
functional form at all.

**A covariate that has to be watched.** Within the walk family, coherence and type-token ratio move
together (TTR 0.84 at w = 0, 0.68 at w = 0.3): greedy nearest-in-meaning selection repeats itself,
which is the trap `weighted_selection` fell into at w = 1. polygon sits at TTR 0.73-0.82 over its
range, comparable to the walk at matched coherence, but the regression is refit with TTR included so
the claim does not rest on that being close enough by eye.

Usage: python3 explore/hypnagogia/coherence_collinearity.py [--smoke]
Outputs (committed): coherence_collinearity.csv, coherence_collinearity_summary.csv,
                     coherence_collinearity.png
"""
import argparse
import importlib.util
import re
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from scipy import stats

from spiritbench.config import load_config, REPO_ROOT
from spiritbench.listener.model import HiddenStateModel
from spiritbench.stimuli import adapter as ad
from spiritbench.stimuli.phrase_bank import load_nrc

HERE = Path(__file__).resolve().parent
SCRATCH = REPO_ROOT / "explore/scratch/rule_vs_text"     # shared, so the 8 existing builds reuse
GEN_PROMPT = "I close my eyes, and what comes to mind is"
WORD = re.compile(r"[a-z']+")
N_GEN, GEN_TOK, N_BOOT, N_LINES = 100, 110, 10000, 16
STARTS = {"S1": (0.50, 0.50), "S2": (0.60, 0.25), "S3": (0.40, 0.45), "S4": (0.70, 0.30)}
WEIGHTS = [0.0, 0.04, 0.07, 0.1, 0.3]


def _mod(name, path):
    s = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(s)
    s.loader.exec_module(m)
    return m


hr = _mod("hr", HERE / "run.py")
ws = _mod("ws", HERE / "weighted_selection.py")
ds = _mod("ds", HERE / "drift_search.py")
cp, hy, rb = hr.cp, hr.hy, hr.rb


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()
    n_gen = 4 if args.smoke else N_GEN
    SCRATCH.mkdir(parents=True, exist_ok=True)

    cfg = load_config()
    nrc = load_nrc(cfg["nrc_lexicon"])
    art = ad.load_art(str(REPO_ROOT / "data/phrase_bank/phrase_graph.json"))
    ok, vocab = cp.clean_mask(art, cfg["glove_path"])
    no_minor = np.array([not (rb.MINOR & set(rb.WORD.findall(art.word(i).lower())))
                         for i in range(len(art.nodes))])
    screen_ok = np.array([not ds.screened(art.word(i)) for i in range(len(art.nodes))])
    mask = ok & no_minor & screen_ok & hr.facet_union(art, hy.FACETS, vocab, cfg["glove_path"])
    tva = tuple(np.mean([[nrc[w][0], nrc[w][1]]
                         for wss in hy.FACETS.values() for w in wss if w in nrc], axis=0))

    # name -> (ids, family, w, origin). walk w=0.3 and polygon keep rule_vs_text's cache names.
    builds = {}
    for k, s in STARTS.items():
        builds[f"polygon_{k}"] = (
            ad.apply_mask_to_path(art, ad.polygon_pca(art, s, tva, N_LINES, 42), mask),
            "polygon", np.nan, k)
        for w in WEIGHTS:
            nm = f"walk_{k}" if w == 0.3 else f"walk_w{int(w * 1000):03d}_{k}"
            builds[nm] = (ws.walk_weighted(art, mask, tva, N_LINES, w, start_va=s), "walk", w, k)

    texts, meta = {}, {}
    for nm, (ids, fam, w, k) in builds.items():
        texts[nm] = ".\n".join(art.word(i) for i in ids)
        tk = [t for i in ids for t in WORD.findall(art.word(i).lower())]
        meta[nm] = dict(build=nm, family=fam, w=w, origin=k,
                        coherence=hr.line_coherence(art, ids),
                        poem_ttr=len(set(tk)) / len(tk), n_distinct=len(set(ids)))
    print(f"{len(builds)} builds · walk coherence "
          f"{min(m['coherence'] for m in meta.values() if m['family'] == 'walk'):.3f}-"
          f"{max(m['coherence'] for m in meta.values() if m['family'] == 'walk'):.3f} · polygon "
          f"{min(m['coherence'] for m in meta.values() if m['family'] == 'polygon'):.3f}-"
          f"{max(m['coherence'] for m in meta.values() if m['family'] == 'polygon'):.3f}\n", flush=True)

    # The 8 builds shared with rule_vs_text reuse its cache. Only trust that cache if this
    # rebuild still produces the identical poem; otherwise drop it and regenerate.
    prev = HERE / "rule_vs_text_poems.md"
    if prev.exists() and not args.smoke:
        for rule, k, body in re.findall(r"## (\w+)@(\w+)[^\n]*\n\n```\n(.*?)\n```",
                                        prev.read_text(), re.S):
            nm = f"{rule}_{k}"
            if nm in texts and body.strip() != texts[nm].strip():
                print(f"  {nm}: poem differs from rule_vs_text, dropping its cache", flush=True)
                (SCRATCH / f"{nm}.csv").unlink(missing_ok=True)
            elif nm in texts:
                print(f"  {nm}: verified identical to rule_vs_text", flush=True)

    model = HiddenStateModel(cfg["listener_model"], device=cfg["device"])
    tok, net, dev = model.tokenizer, model.model, model.device
    pre = cfg["preamble"]
    WV, WK = ds.load_wordvecs(cfg)

    def embed(t):
        ts = [x for x in WORD.findall(t.lower()) if x in WK]
        if not ts:
            return None
        v = WV[[WK[x] for x in ts]].mean(0)
        return v / max(np.linalg.norm(v), 1e-9)

    t0 = time.time()
    rows = []
    for nm, (ids, fam, w, k) in builds.items():
        cpath = SCRATCH / f"{nm}.csv"
        if cpath.exists() and not args.smoke:
            d = pd.read_csv(cpath)
            d["build"] = nm
            rows.append(d)
            print(f"  {nm:<18} cached  drift {d.drift.mean():.4f}", flush=True)
            continue
        ii = tok(pre + texts[nm] + "\n\n" + GEN_PROMPT, return_tensors="pt").to(dev)
        recs = []
        for g in range(n_gen):
            torch.manual_seed(5000 + g)
            with torch.no_grad():
                o = net.generate(**ii, max_new_tokens=GEN_TOK, do_sample=True, temperature=0.9,
                                 top_p=0.95, repetition_penalty=1.2, pad_token_id=tok.eos_token_id)
            txt = tok.decode(o[0, ii["input_ids"].shape[1]:], skip_special_tokens=True)
            es = [e for e in (embed(x) for x in re.split(r"[.!?\n]+", txt) if len(x.split()) > 2)
                  if e is not None]
            hops = [1 - es[i] @ es[i + 1] for i in range(len(es) - 1)]
            toks = WORD.findall(txt.lower())
            recs.append(dict(condition=nm, gen=g, n_hops=len(hops),
                             drift=float(np.mean(hops)) if hops else np.nan,
                             ttr=len(set(toks)) / len(toks) if toks else np.nan,
                             n_tokens=len(toks)))
        d = pd.DataFrame(recs)
        if not args.smoke:
            d.to_csv(cpath, index=False)
        d["build"] = nm
        rows.append(d)
        print(f"  {nm:<18} drift {d.drift.mean():.4f} ({d.drift.notna().sum()} usable) "
              f"[{time.time() - t0:.0f}s]", flush=True)

    df = pd.concat(rows, ignore_index=True)
    df.to_csv(HERE / "coherence_collinearity.csv", index=False)

    boot = np.random.default_rng(0)
    per, summ = {}, []
    for nm in builds:
        v = df[df.build == nm].drift.dropna().to_numpy()
        per[nm] = v
        bs = np.array([boot.choice(v, len(v), True).mean() for _ in range(N_BOOT)])
        summ.append(dict(meta[nm], n=len(v), drift=v.mean(),
                         ci_lo=np.percentile(bs, 2.5), ci_hi=np.percentile(bs, 97.5),
                         mean_hops=df[df.build == nm].n_hops.mean()))
    s = pd.DataFrame(summ).sort_values(["family", "coherence"])
    s.to_csv(HERE / "coherence_collinearity_summary.csv", index=False)
    print("\n" + s.round(4).to_string(index=False))

    wk = s[s.family == "walk"]
    pg = s[s.family == "polygon"]
    print(f"\ncoherence is no longer collinear with family: walk "
          f"{wk.coherence.min():.3f}-{wk.coherence.max():.3f}, polygon "
          f"{pg.coherence.min():.3f}-{pg.coherence.max():.3f}")

    lr = stats.linregress(wk.coherence, wk.drift)
    print(f"\nWALK COHERENCE-RESPONSE CURVE (n={len(wk)}): slope {lr.slope:+.4f} per unit coherence,"
          f" r={lr.rvalue:+.2f}, p={lr.pvalue:.4f}")
    print(f"  over the observed span that is {lr.slope * (wk.coherence.max() - wk.coherence.min()):+.4f} "
          f"of drift — compare the rule effect of +0.0240")

    pred = lr.intercept + lr.slope * pg.coherence
    resid = pg.drift.to_numpy() - pred.to_numpy()
    print(f"\nDO THE POLYGON BUILDS LIE ON IT?")
    for nm, c, d_, p_, r_ in zip(pg.build, pg.coherence, pg.drift, pred, resid):
        print(f"  {nm:<14} coherence {c:.3f}  drift {d_:.4f}  walk-curve predicts {p_:.4f}  "
              f"residual {r_:+.4f}")
    # bootstrap the mean polygon residual, resampling generations within each build
    rb_ = []
    for _ in range(N_BOOT):
        mm = [boot.choice(per[nm], len(per[nm]), True).mean() for nm in pg.build]
        rb_.append(np.mean(np.array(mm) - pred.to_numpy()))
    rb_ = np.array(rb_)
    lo, hi = np.percentile(rb_, [2.5, 97.5])
    print(f"  mean residual {resid.mean():+.4f}  [{lo:+.4f}, {hi:+.4f}]  "
          f"{'ABOVE the curve — geometry does something coherence does not' if lo > 0 else ('BELOW the curve' if hi < 0 else 'ON the curve — consistent with coherence alone')}")

    band = (max(wk.coherence.min(), pg.coherence.min()), min(wk.coherence.max(), pg.coherence.max()))
    wb = wk[(wk.coherence >= band[0]) & (wk.coherence <= band[1])]
    pb = pg[(pg.coherence >= band[0]) & (pg.coherence <= band[1])]
    print(f"\nMATCHED-COHERENCE CONTRAST over {band[0]:.3f}-{band[1]:.3f} "
          f"(no functional form assumed): {len(pb)} polygon vs {len(wb)} walk builds")
    if len(pb) >= 2 and len(wb) >= 2:
        t = stats.ttest_ind(pb.drift, wb.drift)
        print(f"  polygon {pb.drift.mean():.4f} (mean coherence {pb.coherence.mean():.3f})  vs  "
              f"walk {wb.drift.mean():.4f} ({wb.coherence.mean():.3f})")
        print(f"  difference {pb.drift.mean() - wb.drift.mean():+.4f}, t={t.statistic:.2f}, "
              f"p={t.pvalue:.4f}")

    X = np.column_stack([np.ones(len(s)), s.coherence, s.poem_ttr, (s.family == "polygon").astype(float)])
    beta, *_ = np.linalg.lstsq(X, s.drift.to_numpy(), rcond=None)
    resid_full = s.drift.to_numpy() - X @ beta
    se = np.sqrt(np.sum(resid_full ** 2) / (len(s) - 4) * np.diag(np.linalg.inv(X.T @ X)))
    print(f"\ndrift ~ coherence + poem TTR + family, n={len(s)} builds:")
    for nmb, b, e in zip(("intercept", "coherence", "poem_ttr", "family=polygon"), beta, se):
        tv = b / e
        print(f"  {nmb:<16} {b:+.4f}  (se {e:.4f}, t {tv:+.2f}, p {2 * stats.t.sf(abs(tv), len(s) - 4):.4f})")

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    BLUE, ORANGE, INK, MUTED, GRID = "#2a78d6", "#eb6834", "#0b0b0b", "#52514e", "#e2e1dc"
    fig, ax = plt.subplots(figsize=(8.6, 5.2), dpi=120)
    fig.patch.set_facecolor("#fcfcfb"); ax.set_facecolor("#fcfcfb")
    xs = np.linspace(s.coherence.min() - .01, s.coherence.max() + .01, 50)
    ax.plot(xs, lr.intercept + lr.slope * xs, color=ORANGE, lw=1.8, zorder=2,
            label=f"walk curve (r={lr.rvalue:+.2f})")
    ax.axvspan(band[0], band[1], color=GRID, alpha=.55, zorder=0)
    for fam, c, mk in (("walk", ORANGE, "o"), ("polygon", BLUE, "D")):
        q = s[s.family == fam]
        ax.errorbar(q.coherence, q.drift, yerr=[q.drift - q.ci_lo, q.ci_hi - q.drift],
                    fmt=mk, ms=7, color=c, ecolor=INK, elinewidth=1.1, lw=0, zorder=4, label=fam)
    ax.set_xlabel("line coherence"); ax.set_ylabel("associative drift, 95% CI")
    ax.set_title("Does polygon-pca lie on the walk's coherence curve?", fontsize=11, color=INK)
    ax.legend(frameon=False, fontsize=9)
    ax.grid(color=GRID, lw=.6, zorder=0)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"):
        ax.spines[sp].set_color("#c3c2b7")
    ax.tick_params(colors=MUTED, labelsize=8)
    fig.tight_layout()
    fig.savefig(HERE / "coherence_collinearity.png", facecolor=fig.get_facecolor())
    print(f"\nwrote coherence_collinearity.csv coherence_collinearity_summary.csv "
          f"coherence_collinearity.png ({(time.time() - t0) / 60:.1f} min)")


if __name__ == "__main__":
    main()
